name: cs4098
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.3
    - numpy
    - imbalanced-learn
    - matplotlib
    - jupyter
    - seaborn
    - scikit-plot
    - scikit-learn
    - scikit-image
    - tqdm
    - scipy
    - python-graphviz
    - coverage
    - pip:
        - tensorflow==1.4.0
        - keras
